apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "readsb.fullname" . }}
  labels:
    {{- include "readsb.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{- .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: readsb
              servicePort: 8080
            path: /
  tls:
  - hosts:
    - {{- .Values.ingress.host }}
