apiVersion: v1
kind: Service
metadata:
  name: {{ include "readsb.fullname" . }}
  labels:
    {{- include "readsb.labels" . | nindent 4 }}
spec:
  ports:
    - name: "8080"
        port: 8080
        targetPort: 8080
    - name: "30005"
        port: 30005
        targetPort: 30005
  selector:
    app: readsb
status:
  loadBalancer: {}
